[package]
name = "flappy-bird"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
log = "0.4.20"
ratatui = "0.26.0"
simple-logging = "2.0.2"
thiserror = "1.0.57"
